# Generated by Django 4.2.1 on 2023-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_icons/user_default_new.jpg', upload_to='profile_icons'),
        ),
    ]
